### PR TITLE
Checks if directory exists

### PR DESCRIPTION
**Pull request by alvincrespo**
## Changes

- Checks if the directory (`path`) exists before writing to the file

### CODE REVIEW

**Comment by alvincrespo** [comment]
@HugoLnx Thanks for sharing the code to your project here. I was doing some research and came across your project on [elixirforum](https://elixirforum.com/t/application-using-genstage-with-pretty-tracing-for-studying-purposes/12917). When I ran it I received an error related to the directory not existing, so I thought I'd open a PR to help you out with this one. 

Let me know if you have any questions/concerns.

Cheers!

**Comment by HugoLnx** [comment]
Ooops! I remember thinking about how I could not forget about putting `.gitkeep` on `/logs`, but you can see what happened, thanks for the PR <3!

**Comment by HugoLnx** [comment]
@alvincrespo Just for the record, I made a [simple change](https://github.com/HugoLnx/acai-restaurant/commit/319c948c82daf1070389d4f5fe68a80b64ad2a2c) just to use `Path.join/2` instead of concatenating path and filename.
;D

**Comment by alvincrespo** [comment]
@HugoLnx oh awesome! Thanks 😄

**Pull request merged**
